# Allow NGINX ingress controller to reach marketplace-web
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-controller
  namespace: printforge
  labels:
    app.kubernetes.io/part-of: printforge
    policy-type: ingress-allow
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: marketplace-web
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
          podSelector:
            matchLabels:
              app.kubernetes.io/component: controller
      ports:
        - protocol: TCP
          port: 3000
